CREATING ARRAY FROM LIST

In [17]:
import numpy as np 

arr1 = np.array([1,2,3,4,5])
print("1D array : " , arr1)

arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D array : " , arr2)

1D array :  [1 2 3 4 5]
2D array :  [[1 2 3]
 [4 5 6]
 [7 8 9]]


MULTIPLICATION IN LIST Vs ARRAY

In [ ]:
import numpy as np
py_list =[1,2,3]
print("pyhton list multiply : ",py_list*2)

np_array = np.array([1,2,3])
print("numpy array multiplication : ",np_array*2)

pyhton list multiply :  [1, 2, 3, 1, 2, 3]
numpy array multiplication :  [2 4 6]


CHECK TIME LIST VS ARRAY

In [ ]:
import numpy as np 
import time
py_list =[1,2,3]
print("pyhton list multiply : ",py_list*2)

np_array = np.array([1,2,3])
print("numpy array multiplication : ",np_array*2)

start = time.time()
py_list =[i*2 for i in range (100000)]
print("\n List operation time :", time.time()-start)

start = time.time()
np_array = np.arange(100000)*2
print("\n Array operation time :", time.time()-start)

pyhton list multiply :  [1, 2, 3, 1, 2, 3]
numpy array multiplication :  [2 4 6]

 List operation time : 0.008533239364624023

 Array operation time : 0.0063288211822509766


CREATING ARRAY FROM STRATCH

In [ ]:
#---------ZEROS ARRAY---------
import numpy as np 
zeros = np.zeros((3,3))
print("zreos array : \n",zeros)

#---------ONES ARRAY----------
ones = np.ones((3,3))
print("ones array : \n",ones)

#---------FULL ARRAY----------
full = np.full((3,3),9)
print("full array : \n", full)

#---------RANDOM ARRAY--------
random = np.random.random((3,3))
print("random array : \n", random)

#---------SEQUENDIAL ARRAY--------
sequnce = np.arange(1,11,1)
print("sequnce array : \n", sequnce)

zreos array : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones array : 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
full array : 
 [[9 9 9]
 [9 9 9]
 [9 9 9]]
random array : 
 [[0.67512589 0.53967311 0.19000987]
 [0.17557212 0.30873662 0.36907923]
 [0.83794152 0.00247842 0.74816017]]
sequnce array : 
 [ 1  2  3  4  5  6  7  8  9 10]


ARRAY PROPERTY

In [2]:
import numpy as np
arr = np.array([[1,2,3],
               [4,5,6]])
print("shape : ",arr.shape)
print("dimention : ",arr.ndim)
print("size : ",arr.size)


shape :  (2, 3)
dimention :  2
size :  6


RESHAPE ARRAY

In [15]:
import numpy as np 
arr = np.arange(12)
print("arrang array : ",arr)

reshape = arr.reshape((3,4))
print("reshape array : \n",reshape)

transpose = reshape.T
print("transpose array : \n",transpose)

arrang array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshape array : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
transpose array : 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
